name: Export WebApp [ Hackweek ]

on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Build WebApp
        run: |
          yarn
          yarn build
      - name: Uploading artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: ./build
          retention-days: 1
