name: Export WebApp [ Hackweek ]

on:
  workflow_dispatch:
    inputs:
      tag:
        type: input
        description: 'unique tag'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Build WebApp
        run: |
          yarn
          yarn build
      - name: Uploading artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: webapp-${{ github.event.inputs.tagx }}
          path: ./build
          retention-days: 1
